[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/admin/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.railway.app/api/:splat"
  status = 200
  force = true

[build.environment]
  REACT_APP_API_URL = "https://your-backend-url.railway.app/api"