[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
  'cp package.railway.json package.json',
  'npm install'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'
